package com.example.aichat.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    CHARACTER_NOT_FOUND,
    DEBATE_SESSION_NOT_FOUND,
    DEBATE_PARTICIPANT_NOT_FOUND,
    INVALID_SESSION_STATE,
    INVALID_DEBATE_RULE,
    INVALID_PARTICIPANT_COUNT,
    DUPLICATED_SPEAKING_ORDER,
    TURN_GENERATION_FAILED,
    SHARED_CONTENT_NOT_FOUND
}
